import { ConceroNetworkNames } from "../types/ConceroNetwork";

export const networkEnvKeys: Record<ConceroNetworkNames, string> = {
    //test
    localhost: "LOCALHOST",

    // mainnets
    ethereum: "ETHEREUM",
    arbitrum: "ARBITRUM",
    optimism: "OPTIMISM",
    polygon: "POLYGON",
    polygonZkEvm: "POLYGON_ZKEVM",
    avalanche: "AVALANCHE",
    base: "BASE",
    // testnets
    sepolia: "SEPOLIA",
    optimismSepolia: "OPTIMISM_SEPOLIA",
    arbitrumSepolia: "ARBITRUM_SEPOLIA",
    avalancheFuji: "AVALANCHE_FUJI",
    baseSepolia: "BASE_SEPOLIA",
    polygonAmoy: "POLYGON_AMOY",
    lineaSepolia: "LINEA_SEPOLIA",
    bnbTestnet: "BNB_TESTNET",
    soneiumMinato: "SONEIUM_MINATO",
    sonicBlaze: "SONIC_BLAZE",
    astarShibuya: "ASTAR_SHIBUYA",
    roninSaigon: "RONIN_SAIGON",
    megaethTestnet: "MEGAETH_TESTNET",
    berachainBepolia: "BERACHAIN_BEPOLIA",
    sonicBlaze: "SONIC_BLAZE",
    apechainCurtis: "APECHAIN_CURTIS",
    bitlayerTestnet: "BITLAYER_TESTNET",
    blastSepolia: "BLAST_SEPOLIA",
    botanixTestnet: "BOTANIX_TESTNET",
    celoAlfajores: "CELO_ALFAJORES",
    coreTestnet: "CORE_TESTNET",
    cronosTestnet: "CRONOS_TESTNET",
    gnosisChiado: "GNOSIS_CHIADO",
    hashkeyTestnet: "HASHKEY_TESTNET",
    inkSepolia: "INK_SEPOLIA",
    mantleSepolia: "MANTLE_SEPOLIA",
    scrollSepolia: "SCROLL_SEPOLIA",
    seiTestnet: "SEI_TESTNET",
    shibariumPuppynet: "SHIBARIUM_PUPPYNET",
    unichainSepolia: "UNICHAIN_SEPOLIA",
    monadTestnet: "MONAD_TESTNET",
    xlayerSepolia: "XLAYER_SEPOLIA",
    zircuitTestnet: "ZIRCUIT_TESTNET",
    modeTestnet: "MODE_TESTNET",
};
