version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    env_file:
      - ./../.env
      - ./../.env.deployments.testnet
      - ./../.env.deployments.mainnet
    volumes:
      - ../logs:/app/logs
    restart: always
