version: "3.8"

services:
  app:
    container_name: relayer
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    env_file:
      - ./../.env
      - ./../.env.production
    volumes:
      - ../logs:/app/logs
    restart: always
    command: >
      sh -c "
        bunx prisma migrate deploy --schema=prisma/schema.prisma &&
        bun ./dist/index.js
      "
