version: "3.8"

services:
  app:
    container_name: relayer
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    env_file:
      - ./../.env
      - ./../.env.production
    volumes:
      - relayer_logs:/app/logs
    environment:
      NODE_ENV: production
    restart: always


volumes:
  relayer_logs: {}
