name: "relayers"

services:
  app:
    container_name: "relayer"
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    volumes:
      - ../.deploy/loga:/logs
    command: >
      sh -c "
      bun run prisma:migrate:dev &&
      bun run start
      "
    depends_on:
      - postgres

  postgres:
    image: postgres:17.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ../.deploy/postgres:/var/lib/postgresql/data
    container_name: ${DATABASE_HOST}
    hostname: ${DATABASE_HOST}
    ports:
      - ${DATABASE_PORT}:5432
    restart: unless-stopped