import { Log } from "viem";

import { decodeLogs } from "../../common/eventListener/decodeLogs";
import { logger } from "../../common/utils/logger";

import { globalConfig } from "../../constants";
import { ConceroNetwork } from "../../types/ConceroNetwork";
import { requestCLFMessageReport } from "../businessLogic/requestCLFMessageReport";
import { submitCLFMessageReport } from "../businessLogic/submitCLFMessageReport";

export async function onRouterConceroSentLogs(logs: Log[], network: ConceroNetwork) {
    logger.debug(
        `[onRouterConceroSentLogs] Processing ${logs.length} ConceroMessageSent logs from ${network.name}`,
    );

    const promises = [];

    for (const log of logs) {
        promises.push(requestCLFMessageReport(log, network.chainSelector));
    }

    await Promise.all(promises);
}

/**
 * Handle MessageReport events from ConceroVerifier.
 * This is triggered when a message report is generated by the verifier.
 */
export async function onVerifierMessageReportLogs(logs: Log[], network: ConceroNetwork) {
    logger.debug(`[onVerifierMessageReportLogs] Processing ${logs.length} MessageReport logs`);

    const promises = [];

    for (const log of logs) {
        promises.push(submitCLFMessageReport(log));
    }

    await Promise.all(promises);
}

/**
 * Handle ConceroMessageReceived events from ConceroRouter.
 * This is triggered when a message is received on a destination chain.
 */
// export async function onRouterConceroReceivedLogs(logs: Log[], network: ConceroNetwork) {
//     if (logs.length === 0) return;

//     logger.debug(
//         `[onRouterConceroReceivedLogs] Processing ${logs.length} ConceroMessageReceived logs from ${network.name}`,
//     );

//     const decodedLogs = decodeLogs(logs, globalConfig.ABI.CONCERO_ROUTER);
//     const promises = [];

//     for (const log of decodedLogs) {
//         if (log.eventName === "ConceroMessageReceived") {
//             // Place your business logic here, e.g.:
//             // promises.push(handleConceroMessageReceived(log, network));
//         }
//     }

//     if (promises.length) {
//         await Promise.all(promises);
//     }
// }

/**
 * Handle MessageReportRequested events from ConceroVerifier.
 * This is triggered when a message report is requested from the verifier.
 */
// export async function onVerifierMessageReportRequestedLogs(logs: Log[], network: ConceroNetwork) {
//     if (logs.length === 0) return;

//     logger.debug(
//         `[onVerifierMessageReportRequestedLogs] Processing ${logs.length} MessageReportRequested logs`,
//     );

//     const decodedLogs = decodeLogs(logs, globalConfig.ABI.CONCERO_VERIFIER);
//     const promises = [];

//     for (const log of decodedLogs) {
//         if (log.eventName === "MessageReportRequested") {
//             // Place your business logic here, e.g.:
//             // promises.push(handleMessageReportRequested(log, network));
//         }
//     }

//     if (promises.length) {
//         await Promise.all(promises);
//     }
// }
