name: Deploy Concero Relayer

on:
  push:
    branches:
      - mainnet
      - testnet
      - stage

jobs:
  deploy:
    name: Deploy Relayer
    runs-on: ubuntu-latest

    steps:
      # ----------------- Checkout -----------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ----------------- Define environment -----------------
      - name: Define environment
        id: env
        run: |
          if [ "${GITHUB_REF}" == "refs/heads/mainnet" ]; then
            ENV=mainnet
          elif [ "${GITHUB_REF}" == "refs/heads/testnet" ]; then
            ENV=testnet
          elif [ "${GITHUB_REF}" == "refs/heads/stage" ]; then
            ENV=stage
          else
            echo "❌ Unsupported branch"
            exit 1
          fi
          echo "env=$ENV" >> $GITHUB_OUTPUT

      # ----------------- Define branch -----------------
      - name: Define branch
        id: branch
        run: |
          if [ "${{ steps.env.outputs.env }}" == "mainnet" ]; then
            echo "branch=mainnet" >> $GITHUB_OUTPUT
          elif [ "${{ steps.env.outputs.env }}" == "testnet" ]; then
            echo "branch=testnet" >> $GITHUB_OUTPUT
          else
            echo "branch=stage" >> $GITHUB_OUTPUT
          fi

      # ----------------- Deploy -----------------
      - name: Deploy to environment
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ steps.env.outputs.env == 'mainnet' && secrets.MAINNET_SSH_HOST ||
            steps.env.outputs.env == 'testnet' && secrets.TESTNET_SSH_HOST ||
            steps.env.outputs.env == 'stage' && secrets.STAGE_SSH_HOST }}
          username: ${{ steps.env.outputs.env == 'mainnet' && secrets.MAINNET_SSH_USER ||
            steps.env.outputs.env == 'testnet' && secrets.TESTNET_SSH_USER ||
            steps.env.outputs.env == 'stage' && secrets.STAGE_SSH_USER }}
          key: ${{ steps.env.outputs.env == 'mainnet' && secrets.MAINNET_SSH_KEY ||
            steps.env.outputs.env == 'testnet' && secrets.TESTNET_SSH_KEY ||
            steps.env.outputs.env == 'stage' && secrets.STAGE_SSH_KEY }}
          port: ${{ steps.env.outputs.env == 'mainnet' && secrets.MAINNET_SSH_PORT ||
            steps.env.outputs.env == 'testnet' && secrets.TESTNET_SSH_PORT ||
            steps.env.outputs.env == 'stage' && secrets.STAGE_SSH_PORT }}
          script: |
            echo "🚀 Deploying Concero Relayer → ${{ steps.env.outputs.env }}"
            cd /root/relayer
            git fetch --all
            git reset --hard ${{ steps.branch.outputs.branch }}
            docker compose --env-file .env -f docker/docker-compose.yml up --build -d
            echo "✅ ${{ steps.env.outputs.env }} done at $(date)"